apiVersion: apps/v1
kind: Deployment
metadata:
  name: e02-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpService
  template:
    metadata:
      labels:
        app: httpService
    spec:
      containers:
        - name: http-service
          image: e01-spring:0.0.1
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          ports:
            - containerPort: 8080